### ISSUE TITLE
CSS Auto-Sync Not Working

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/BrowserLink#62]
When I make a change to `wwwroot\css\site.css` and I have browser link connected to Chrome, shouldn't Chrome automatically update?

I'm using VS 2017: 15.4 for an Asp.Net Core 1.1 MVC web app.  I started with the MVC template and deleted some stuff I don't need.

![image](https://user-images.githubusercontent.com/14079228/31443698-31ea2a46-ae68-11e7-944a-438745ce7af3.png)

![image](https://user-images.githubusercontent.com/14079228/31443888-96e9ce42-ae68-11e7-8248-4c12c801d603.png)

What **other info** can I provide to track this down?

**Comment by nhwilly** [comment]
Same here.  vs 15.4.1, .Net Core 1.1 - manual refresh works, but nothing else does.  And that's only if I save the file first.  That's to be expected though, right?

**Comment by spottedmahn** [comment]
No, that is not to be expected per [Enable or Disable CSS Auto Sync](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-browserlink?tabs=aspnetcore1x#enable-or-disable-css-auto-sync):

>When CSS Auto-Sync is enabled, connected browsers are automatically refreshed when you make any change to CSS files.

**Comment by redpeaks33** [comment]
try this. it works for me.
https://docs.microsoft.com/en-us/aspnet/visual-studio/overview/2013/using-browser-link#enabling-browser-link-for-static-html-files

**Comment by spottedmahn** [comment]
thanks @redpeaks33!  I'll give that a try!

**Comment by brunolau** [comment]
Is there a way to identify what's the cause? 

I'm having the very same issue. When I create a brand new project using ASP.NET classic MVC template, CSS sync works, when I create a brand new project for ASP.NET MVC Core [New project => Web Application (MVC), app.UseBrowserLink() is present], CSS doesn't sync

VS 15.6.2
.NET Core 2.0

**Comment by WereDev** [comment]
So it looks like this was closed, but was there a resolution to this?  I'm using VS 15.8.4 and .Net Core 2.1 and it still doesn't work.  Yes I used NuGet to get Microsoft.VisualStudio.Web.BrowserLink and yes I have app.UseBrowserLink().  I can see the browser is connected, but css and other static files are not being updated.

**Comment by spottedmahn** [comment]
I threw in the towel and moved on.

**Comment by WereDev** [comment]
I'm sad that this hasn't been addressed because in a situation when one is doing Typescript (eg Angular) work, those generally get compiled and dropped into the wwwroot folder so it would be nice that I it would refresh as I change things.  As it is I need to use ngserve and break that out during dev so that I can maintain a decent development process which then means it's not like deployment which has already caused a few issues.
